.nh
.TH "GH-GIST-DELETE" "1" "Oct 2024" "GitHub CLI 2.58.0" "GitHub CLI manual"

.SH NAME
gh-gist-delete - Delete a gist


.SH SYNOPSIS
\fBgh gist delete {<id> | <url>} [flags]\fR


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-gist(1)\fR
