.nh
.TH "GH-GIST-LIST" "1" "Oct 2024" "GitHub CLI 2.58.0" "GitHub CLI manual"

.SH NAME
gh-gist-list - List your gists


.SH SYNOPSIS
\fBgh gist list [flags]\fR


.SH OPTIONS
.TP
\fB-L\fR, \fB--limit\fR \fB<int> (default 10)\fR
Maximum number of gists to fetch

.TP
\fB--public\fR
Show only public gists

.TP
\fB--secret\fR
Show only secret gists


.SH ALIASES
gh gist ls


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-gist(1)\fR
