.nh
.TH "GH-AUTH-TOKEN" "1" "Nov 2023" "GitHub CLI 2.38.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth-token - Print the auth token gh is configured to use


.SH SYNOPSIS
.PP
\fBgh auth token [flags]\fR


.SH OPTIONS
.TP
\fB-h\fR, \fB--hostname\fR \fB<string>\fR
The hostname of the GitHub instance authenticated with


.SH SEE ALSO
.PP
\fBgh-auth(1)\fR
