.nh
.TH "GH-AUTH" "1" "Nov 2023" "GitHub CLI 2.38.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth - Authenticate gh and git with GitHub


.SH SYNOPSIS
.PP
\fBgh auth <command> [flags]\fR


.SH AVAILABLE COMMANDS
.TP
\fBgh-auth-login(1)\fR
Authenticate with a GitHub host

.TP
\fBgh-auth-logout(1)\fR
Log out of a GitHub host

.TP
\fBgh-auth-refresh(1)\fR
Refresh stored authentication credentials

.TP
\fBgh-auth-setup-git(1)\fR
Setup git with GitHub CLI

.TP
\fBgh-auth-status(1)\fR
View authentication status

.TP
\fBgh-auth-token(1)\fR
Print the auth token gh is configured to use


.SH SEE ALSO
.PP
\fBgh(1)\fR
